# Generated by Django 3.0.1 on 2020-10-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalsection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
