# Generated by Django 3.0.1 on 2020-10-27 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signalsection', '0003_auto_20201027_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email is already registered in the database.'}, max_length=50, null=True, unique=True),
        ),
    ]
