# Generated by Django 3.0.1 on 2020-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalsection', '0008_auto_20201028_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.CharField(default='', max_length=255),
        ),
    ]
