# Generated by Django 3.0.1 on 2020-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201025_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowaccess',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
