# Generated by Django 3.0.1 on 2020-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_allowaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_newslettermanager',
            field=models.BooleanField(blank=True, help_text='let this user send newsletters', null=True, verbose_name='is newsletter manager'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_signalmanager',
            field=models.BooleanField(blank=True, help_text='let this user post signals', null=True, verbose_name='is signal manager'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allowaccess',
            field=models.BooleanField(blank=True, help_text='allow access to signals', null=True, verbose_name='allow access'),
        ),
    ]
