# Generated by Django 3.0.1 on 2020-10-25 19:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201025_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='We will be sending you signals through this phone number.', max_length=30, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='We will be sending you signals through this phone number.', max_length=30, null=True, region=None, unique=True),
        ),
    ]
