# Generated by Django 3.0.1 on 2020-10-28 05:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='We will be sending you signals through this phone number.', max_length=30, null=True, region=None, unique=True),
        ),
    ]
